#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

// конфиг проекта
const OUTPUT_DIR_PATH = __DIR__ . '/output/' ;
const STORAGE_DIR_PATH = __DIR__ . '/storage/';

if (count($argv) < 2) {
    die("Usage: php converter [command] [path-to-file] \n
        Example: php converter convert:json offices.txt
    ");
}

if (!$argv[2]) {
    die("Path not found in the command\n");
}

$command = $argv[1];
$sourcePath = $argv[2];

$commandMap = [
    'convert:json' => 'JsonConvertCommand',
    'convert:xml'  => 'XmlConvertCommand',
];

if (!array_key_exists($command, $commandMap)) {
    die("Unknown command: $command\n");
}

$commandClassName = "OfficeConverter\\Command\\" . $commandMap[$command];

// run
(new $commandClassName())->execute($sourcePath);