#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$argv = $_SERVER['argv'];
array_shift($argv); // убрать имя скрипта

$kernel = new App\UI\CLI\Kernel();
$exitCode = $kernel->handle($argv);

exit($exitCode);