version: '3'
services:
  app:
    container_name: offices-convert
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/app/output
      - ./src:/app/src
      - ./storage:/app/storage
      - ./tests:/app/tests
      - ./vendor:/app/vendor
    tty: true
    user: "${UID}:${GID}"